### ISSUE TITLE
VirtualizingWrapPanel can crash during MeasureOverride

### ISSUE THREAD

**Issue by digimezzo** [digimezzo/WPFControls#11]
This crash happens for 1 user in Dopamine. No idea how to reproduce it though. This is the relevant part of the log:

```
2017-06-10 11:44:32.085|Error|App.ExecuteEmergencyStop|Unhandled Exception. Exception:
System.NullReferenceException: Object reference not set to an instance of an object.
   at Digimezzo.WPFControls.VirtualizingWrapPanel.MeasureOverride(Size availableSize)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Stack trace:
   at Digimezzo.WPFControls.VirtualizingWrapPanel.MeasureOverride(Size availableSize)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg)
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget)
   at System.Windows.Media.MediaContext.RenderMessageHandler(Object resizedCompositionTarget)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by julesx** [comment]
happens to me when i try to sort the items in the panel

**Comment by digimezzo** [comment]
@julesx What do you mean by "sort". Does it happen when sorting items using the sort options in Dopamine? Or are you using the WrapPanel in some custom application?
I have a hard time replicating this issue, but would like to fix it, as users are suffering from it.

**Comment by digimezzo** [comment]
@julesx Can you tell me if you're still having this issue? If yes, how can I reproduce it?
